### ISSUE TITLE
Build to Android failed: unknown output extension

### ISSUE THREAD

**Issue by rottor** [nmehost/gm2d#1]
I'm trying to compile gm2d Particles sample to Android target and getting such an error in the end of the compilation:

```
[dex] Converting compiled files and external libraries into C:\HaxeToolkit
\haxe\lib\gm2d\3,1,2\samples\4-Particles\bin\android\ParticlesTest\bin\classes.d
ex...
       [dx] unknown output extension: C:\HaxeToolkit\haxe\lib\gm2d\3
...

BUILD FAILED
C:\Development\Android SDK\tools\ant\build.xml:892: The following error occurred
 while executing this line:
C:\Development\Android SDK\tools\ant\build.xml:894: The following error occurred
 while executing this line:
C:\Development\Android SDK\tools\ant\build.xml:906: The following error occurred
 while executing this line:
C:\Development\Android SDK\tools\ant\build.xml:284: null returned: 1
```

Full output is available here: http://pastebin.com/C8WXbr1u

Haxe 3.1, NME 5.0.29, Android NDK r9d, Win7

**Comment by hughsando** [comment]
Looks like an error trying to build the example from within the HaxeToolkit Directory, which contains commas.  Try copying the sample folder elsewhere (eg, home/documents directory).  I will see if I can reproduce it.

**Comment by rottor** [comment]
yes, you're right, copying the sample to other folder have helped, thank you!
